/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package Hello.Services.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the NhanVien service. Represents a row in the &quot;neo_NhanVien&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link Hello.Services.model.impl.NhanVienModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Hello.Services.model.impl.NhanVienImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NhanVien
 * @see Hello.Services.model.impl.NhanVienImpl
 * @see Hello.Services.model.impl.NhanVienModelImpl
 * @generated
 */
@ProviderType
public interface NhanVienModel extends BaseModel<NhanVien>, GroupedModel,
	ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a nhan vien model instance should use the {@link NhanVien} interface instead.
	 */

	/**
	 * Returns the primary key of this nhan vien.
	 *
	 * @return the primary key of this nhan vien
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this nhan vien.
	 *
	 * @param primaryKey the primary key of this nhan vien
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this nhan vien.
	 *
	 * @return the uuid of this nhan vien
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this nhan vien.
	 *
	 * @param uuid the uuid of this nhan vien
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this nhan vien.
	 *
	 * @return the ID of this nhan vien
	 */
	public long getId();

	/**
	 * Sets the ID of this nhan vien.
	 *
	 * @param Id the ID of this nhan vien
	 */
	public void setId(long Id);

	/**
	 * Returns the group ID of this nhan vien.
	 *
	 * @return the group ID of this nhan vien
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this nhan vien.
	 *
	 * @param groupId the group ID of this nhan vien
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this nhan vien.
	 *
	 * @return the company ID of this nhan vien
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this nhan vien.
	 *
	 * @param companyId the company ID of this nhan vien
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this nhan vien.
	 *
	 * @return the user ID of this nhan vien
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this nhan vien.
	 *
	 * @param userId the user ID of this nhan vien
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this nhan vien.
	 *
	 * @return the user uuid of this nhan vien
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this nhan vien.
	 *
	 * @param userUuid the user uuid of this nhan vien
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this nhan vien.
	 *
	 * @return the user name of this nhan vien
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this nhan vien.
	 *
	 * @param userName the user name of this nhan vien
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this nhan vien.
	 *
	 * @return the create date of this nhan vien
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this nhan vien.
	 *
	 * @param createDate the create date of this nhan vien
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this nhan vien.
	 *
	 * @return the modified date of this nhan vien
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this nhan vien.
	 *
	 * @param modifiedDate the modified date of this nhan vien
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ten nv of this nhan vien.
	 *
	 * @return the ten nv of this nhan vien
	 */
	@AutoEscape
	public String getTenNV();

	/**
	 * Sets the ten nv of this nhan vien.
	 *
	 * @param TenNV the ten nv of this nhan vien
	 */
	public void setTenNV(String TenNV);

	/**
	 * Returns the gioi tinh of this nhan vien.
	 *
	 * @return the gioi tinh of this nhan vien
	 */
	public boolean getGioiTinh();

	/**
	 * Returns <code>true</code> if this nhan vien is gioi tinh.
	 *
	 * @return <code>true</code> if this nhan vien is gioi tinh; <code>false</code> otherwise
	 */
	public boolean isGioiTinh();

	/**
	 * Sets whether this nhan vien is gioi tinh.
	 *
	 * @param GioiTinh the gioi tinh of this nhan vien
	 */
	public void setGioiTinh(boolean GioiTinh);

	/**
	 * Returns the email of this nhan vien.
	 *
	 * @return the email of this nhan vien
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this nhan vien.
	 *
	 * @param Email the email of this nhan vien
	 */
	public void setEmail(String Email);

	/**
	 * Returns the ngay sinh of this nhan vien.
	 *
	 * @return the ngay sinh of this nhan vien
	 */
	public Date getNgaySinh();

	/**
	 * Sets the ngay sinh of this nhan vien.
	 *
	 * @param NgaySinh the ngay sinh of this nhan vien
	 */
	public void setNgaySinh(Date NgaySinh);

	/**
	 * Returns the dia chi of this nhan vien.
	 *
	 * @return the dia chi of this nhan vien
	 */
	@AutoEscape
	public String getDiaChi();

	/**
	 * Sets the dia chi of this nhan vien.
	 *
	 * @param DiaChi the dia chi of this nhan vien
	 */
	public void setDiaChi(String DiaChi);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(NhanVien nhanVien);

	@Override
	public int hashCode();

	@Override
	public CacheModel<NhanVien> toCacheModel();

	@Override
	public NhanVien toEscapedModel();

	@Override
	public NhanVien toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}