/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package Hello.Services.model.impl;

import Hello.Services.model.NhanVien;
import Hello.Services.model.NhanVienModel;
import Hello.Services.model.NhanVienSoap;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the NhanVien service. Represents a row in the &quot;neo_NhanVien&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link NhanVienModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NhanVienImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NhanVienImpl
 * @see NhanVien
 * @see NhanVienModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class NhanVienModelImpl extends BaseModelImpl<NhanVien>
	implements NhanVienModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a nhan vien model instance should use the {@link NhanVien} interface instead.
	 */
	public static final String TABLE_NAME = "neo_NhanVien";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "Id", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "TenNV", Types.VARCHAR },
			{ "GioiTinh", Types.BOOLEAN },
			{ "Email", Types.VARCHAR },
			{ "NgaySinh", Types.TIMESTAMP },
			{ "DiaChi", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("TenNV", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("GioiTinh", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("Email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("NgaySinh", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("DiaChi", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table neo_NhanVien (uuid_ VARCHAR(75) null,Id LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,TenNV VARCHAR(75) null,GioiTinh BOOLEAN,Email VARCHAR(75) null,NgaySinh DATE null,DiaChi VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table neo_NhanVien";
	public static final String ORDER_BY_JPQL = " ORDER BY nhanVien.TenNV ASC";
	public static final String ORDER_BY_SQL = " ORDER BY neo_NhanVien.TenNV ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(Hello.Services.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.Hello.Services.model.NhanVien"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(Hello.Services.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.Hello.Services.model.NhanVien"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(Hello.Services.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.Hello.Services.model.NhanVien"),
			true);
	public static final long GIOITINH_COLUMN_BITMASK = 1L;
	public static final long COMPANYID_COLUMN_BITMASK = 2L;
	public static final long GROUPID_COLUMN_BITMASK = 4L;
	public static final long UUID_COLUMN_BITMASK = 8L;
	public static final long TENNV_COLUMN_BITMASK = 16L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static NhanVien toModel(NhanVienSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		NhanVien model = new NhanVienImpl();

		model.setUuid(soapModel.getUuid());
		model.setId(soapModel.getId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTenNV(soapModel.getTenNV());
		model.setGioiTinh(soapModel.isGioiTinh());
		model.setEmail(soapModel.getEmail());
		model.setNgaySinh(soapModel.getNgaySinh());
		model.setDiaChi(soapModel.getDiaChi());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<NhanVien> toModels(NhanVienSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<NhanVien> models = new ArrayList<NhanVien>(soapModels.length);

		for (NhanVienSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(Hello.Services.service.util.ServiceProps.get(
				"lock.expiration.time.Hello.Services.model.NhanVien"));

	public NhanVienModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return NhanVien.class;
	}

	@Override
	public String getModelClassName() {
		return NhanVien.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("Id", getId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("TenNV", getTenNV());
		attributes.put("GioiTinh", isGioiTinh());
		attributes.put("Email", getEmail());
		attributes.put("NgaySinh", getNgaySinh());
		attributes.put("DiaChi", getDiaChi());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long Id = (Long)attributes.get("Id");

		if (Id != null) {
			setId(Id);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String TenNV = (String)attributes.get("TenNV");

		if (TenNV != null) {
			setTenNV(TenNV);
		}

		Boolean GioiTinh = (Boolean)attributes.get("GioiTinh");

		if (GioiTinh != null) {
			setGioiTinh(GioiTinh);
		}

		String Email = (String)attributes.get("Email");

		if (Email != null) {
			setEmail(Email);
		}

		Date NgaySinh = (Date)attributes.get("NgaySinh");

		if (NgaySinh != null) {
			setNgaySinh(NgaySinh);
		}

		String DiaChi = (String)attributes.get("DiaChi");

		if (DiaChi != null) {
			setDiaChi(DiaChi);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getId() {
		return _Id;
	}

	@Override
	public void setId(long Id) {
		_Id = Id;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getTenNV() {
		if (_TenNV == null) {
			return "";
		}
		else {
			return _TenNV;
		}
	}

	@Override
	public void setTenNV(String TenNV) {
		_columnBitmask = -1L;

		_TenNV = TenNV;
	}

	@JSON
	@Override
	public boolean getGioiTinh() {
		return _GioiTinh;
	}

	@JSON
	@Override
	public boolean isGioiTinh() {
		return _GioiTinh;
	}

	@Override
	public void setGioiTinh(boolean GioiTinh) {
		_columnBitmask |= GIOITINH_COLUMN_BITMASK;

		if (!_setOriginalGioiTinh) {
			_setOriginalGioiTinh = true;

			_originalGioiTinh = _GioiTinh;
		}

		_GioiTinh = GioiTinh;
	}

	public boolean getOriginalGioiTinh() {
		return _originalGioiTinh;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_Email == null) {
			return "";
		}
		else {
			return _Email;
		}
	}

	@Override
	public void setEmail(String Email) {
		_Email = Email;
	}

	@JSON
	@Override
	public Date getNgaySinh() {
		return _NgaySinh;
	}

	@Override
	public void setNgaySinh(Date NgaySinh) {
		_NgaySinh = NgaySinh;
	}

	@JSON
	@Override
	public String getDiaChi() {
		if (_DiaChi == null) {
			return "";
		}
		else {
			return _DiaChi;
		}
	}

	@Override
	public void setDiaChi(String DiaChi) {
		_DiaChi = DiaChi;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				NhanVien.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			NhanVien.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public NhanVien toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (NhanVien)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		NhanVienImpl nhanVienImpl = new NhanVienImpl();

		nhanVienImpl.setUuid(getUuid());
		nhanVienImpl.setId(getId());
		nhanVienImpl.setGroupId(getGroupId());
		nhanVienImpl.setCompanyId(getCompanyId());
		nhanVienImpl.setUserId(getUserId());
		nhanVienImpl.setUserName(getUserName());
		nhanVienImpl.setCreateDate(getCreateDate());
		nhanVienImpl.setModifiedDate(getModifiedDate());
		nhanVienImpl.setTenNV(getTenNV());
		nhanVienImpl.setGioiTinh(isGioiTinh());
		nhanVienImpl.setEmail(getEmail());
		nhanVienImpl.setNgaySinh(getNgaySinh());
		nhanVienImpl.setDiaChi(getDiaChi());

		nhanVienImpl.resetOriginalValues();

		return nhanVienImpl;
	}

	@Override
	public int compareTo(NhanVien nhanVien) {
		int value = 0;

		value = getTenNV().compareTo(nhanVien.getTenNV());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof NhanVien)) {
			return false;
		}

		NhanVien nhanVien = (NhanVien)obj;

		long primaryKey = nhanVien.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		NhanVienModelImpl nhanVienModelImpl = this;

		nhanVienModelImpl._originalUuid = nhanVienModelImpl._uuid;

		nhanVienModelImpl._originalGroupId = nhanVienModelImpl._groupId;

		nhanVienModelImpl._setOriginalGroupId = false;

		nhanVienModelImpl._originalCompanyId = nhanVienModelImpl._companyId;

		nhanVienModelImpl._setOriginalCompanyId = false;

		nhanVienModelImpl._setModifiedDate = false;

		nhanVienModelImpl._originalGioiTinh = nhanVienModelImpl._GioiTinh;

		nhanVienModelImpl._setOriginalGioiTinh = false;

		nhanVienModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<NhanVien> toCacheModel() {
		NhanVienCacheModel nhanVienCacheModel = new NhanVienCacheModel();

		nhanVienCacheModel.uuid = getUuid();

		String uuid = nhanVienCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			nhanVienCacheModel.uuid = null;
		}

		nhanVienCacheModel.Id = getId();

		nhanVienCacheModel.groupId = getGroupId();

		nhanVienCacheModel.companyId = getCompanyId();

		nhanVienCacheModel.userId = getUserId();

		nhanVienCacheModel.userName = getUserName();

		String userName = nhanVienCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			nhanVienCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			nhanVienCacheModel.createDate = createDate.getTime();
		}
		else {
			nhanVienCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			nhanVienCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			nhanVienCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		nhanVienCacheModel.TenNV = getTenNV();

		String TenNV = nhanVienCacheModel.TenNV;

		if ((TenNV != null) && (TenNV.length() == 0)) {
			nhanVienCacheModel.TenNV = null;
		}

		nhanVienCacheModel.GioiTinh = isGioiTinh();

		nhanVienCacheModel.Email = getEmail();

		String Email = nhanVienCacheModel.Email;

		if ((Email != null) && (Email.length() == 0)) {
			nhanVienCacheModel.Email = null;
		}

		Date NgaySinh = getNgaySinh();

		if (NgaySinh != null) {
			nhanVienCacheModel.NgaySinh = NgaySinh.getTime();
		}
		else {
			nhanVienCacheModel.NgaySinh = Long.MIN_VALUE;
		}

		nhanVienCacheModel.DiaChi = getDiaChi();

		String DiaChi = nhanVienCacheModel.DiaChi;

		if ((DiaChi != null) && (DiaChi.length() == 0)) {
			nhanVienCacheModel.DiaChi = null;
		}

		return nhanVienCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", Id=");
		sb.append(getId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", TenNV=");
		sb.append(getTenNV());
		sb.append(", GioiTinh=");
		sb.append(isGioiTinh());
		sb.append(", Email=");
		sb.append(getEmail());
		sb.append(", NgaySinh=");
		sb.append(getNgaySinh());
		sb.append(", DiaChi=");
		sb.append(getDiaChi());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("Hello.Services.model.NhanVien");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TenNV</column-name><column-value><![CDATA[");
		sb.append(getTenNV());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>GioiTinh</column-name><column-value><![CDATA[");
		sb.append(isGioiTinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Email</column-name><column-value><![CDATA[");
		sb.append(getEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NgaySinh</column-name><column-value><![CDATA[");
		sb.append(getNgaySinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DiaChi</column-name><column-value><![CDATA[");
		sb.append(getDiaChi());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = NhanVien.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			NhanVien.class, ModelWrapper.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _Id;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _TenNV;
	private boolean _GioiTinh;
	private boolean _originalGioiTinh;
	private boolean _setOriginalGioiTinh;
	private String _Email;
	private Date _NgaySinh;
	private String _DiaChi;
	private long _columnBitmask;
	private NhanVien _escapedModel;
}